chef/license-acceptance

README.md
components/golang/chef-license.go
components/golang/config.go
components/golang/config/development.toml
components/golang/habitat/README.md
components/golang/habitat/default.toml
components/golang/product.go
components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/lib/license_acceptance/arg_acceptance.rb
components/ruby/lib/license_acceptance/cli_flags/mixlib_cli.rb
components/ruby/lib/license_acceptance/cli_flags/thor.rb
components/ruby/lib/license_acceptance/env_acceptance.rb
components/ruby/lib/license_acceptance/file_acceptance.rb
components/ruby/lib/license_acceptance/product_reader.rb
components/ruby/lib/license_acceptance/prompt_acceptance.rb
components/ruby/license-acceptance.gemspec
components/ruby/spec/license_acceptance/acceptor_spec.rb
components/ruby/spec/license_acceptance/arg_acceptance_spec.rb
components/ruby/spec/license_acceptance/cli_flags/mixlib_cli_spec.rb
components/ruby/spec/license_acceptance/cli_flags/thor_spec.rb
components/ruby/spec/license_acceptance/env_acceptance_spec.rb
components/ruby/spec/license_acceptance/file_acceptance_spec.rb
components/ruby/spec/license_acceptance/product_reader_spec.rb
components/ruby/spec/license_acceptance/prompt_acceptance_spec.rb
components/ruby/spec/spec_helper.rb

This is a laundry list of changes I wanted to make before products start consuming this. Each commit is 1 TODO/feature
N/A

A bunch of pending TODOs 

---

.expeditor/verify.pipeline.yml

Fixing Ruby tests in pipeline

---

.expeditor/config.yml

Should build gems on PR merge and only publish to Rubygems.com on promote
N/A

Build and publish gem with Expeditor

---

.expeditor/config.yml
.expeditor/copy_product_info.sh
.expeditor/verify.pipeline.yml
components/ruby/.gitignore
components/ruby/.travis.yml
components/ruby/Gemfile.lock
components/ruby/config/product_info.toml
components/ruby/license-acceptance.gemspec
product_info.toml

* Add script to copy product_info.toml to appropriate packaging folder
* Fix warnings issued when building the gem
* We no longer need travis config since we verify in buildkite
N/A

Fixing expeditor config, see description

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
.github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
.github/PULL_REQUEST_TEMPLATE.md
.github/lock.yml
CODE_OF_CONDUCT.md

Set this repo up to comply with our new OSS guidelines
Make sure we have all the configs necessary for outside contributors to be successful including our CoC, templates for PRs / issues, codeowners for reviews, and status info in the readme.
Nope

Set this repo up to comply with our new OSS guidelines

---

components/ruby/README.md

For incoming chef dev docs
N/A

Updating the Ruby README for clarity about config settings

---

README.md
components/ruby/spec/license_acceptance/acceptor_spec.rb
components/ruby/spec/license_acceptance/strategy/file_spec.rb
product_info.toml

We renamed Chef Client to Chef Infra and are rolling this change out
across our suite. Getting it started here.
N/A

Chef Infra is the new/correct name

---

components/ruby/config/product_info.toml

These are from the downloads page.

Use the marketing names for the pretty names

---

product_info.toml

Signed-off-by: Mark Anderson <mark@chef.io>
Add chef-server and push-jobs server dependencies.
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

Add chef server transitive dependencies

---

.expeditor/verify.pipeline.yml
README.md

Environment variables should be quoted

---

.expeditor/verify.pipeline.yml
components/ruby/license-acceptance.gemspec
product_info.toml

Adding product support for ChefDK and Chef Workstation

---

components/ruby/lib/license_acceptance/config.rb

Signed-off-by: tyler-ball <tball@chef.io>

HOMEDRIVE is not set by default on windows 2012r2

---

components/ruby/license-acceptance.gemspec

Signed-off-by: tyler-ball <tball@chef.io>

Must support Ruby 2.3 for Test Kitchen 1.x

---

product_info.toml

Signed-off-by: Mark Anderson <mark@chef.io>
Push Jobs Client was missing from the matrix; this adds it, along with appropriate dependencies

Add Push Jobs Client to matrix

---

components/ruby/lib/license_acceptance/config.rb

Thank you https://github.com/iserje and https://github.com/Tensibai for the issues and suggested fixes! I lack Windows knowledge so thank you for helping me out here.
Fixes https://github.com/chef/license-acceptance/issues/50
Fixes https://github.com/chef/license-acceptance/issues/45
N/A

Use more appropriate SYSTEMDRIVE for WinRM connections without a user

---

components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/spec/license_acceptance/acceptor_spec.rb

Thank you https://github.com/FooBarWidget for the report and suggested
fix!
Fixes https://github.com/chef/license-acceptance/issues/46

TK can supply chef version as :latest or 'latest'

---

.expeditor/config.yml
.expeditor/verify.pipeline.yml

Also send build information to chef-found-notify now that the license
acceptance project has shipped.

Fix failures in BK and speed up builds

---

.expeditor/update_version.sh

Dependabot will handle updating dependencies as they come in. This is
better than blindly doing a 'bundle update' every time we merge a PR.
N/A

Use dependabot to update dependencies rather than blindly updating

---

README.md
components/ruby/lib/license_acceptance/strategy/prompt.rb
components/ruby/spec/license_acceptance/strategy/argument_spec.rb

Fix minor spelling mistakes

---

components/ruby/lib/license_acceptance/product_reader.rb
components/ruby/lib/license_acceptance/strategy/file.rb
components/ruby/lib/license_acceptance/strategy/prompt.rb

These autoloads shave about 600-700ms on my windows laptop.
Signed-off-by: mwrock <matt@mattwrock.com>

improve initial load perf with autoloading expensive gems

---

components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/lib/license_acceptance/logger.rb
components/ruby/lib/license_acceptance/product_reader.rb
components/ruby/lib/license_acceptance/strategy/argument.rb
components/ruby/lib/license_acceptance/strategy/environment.rb
components/ruby/lib/license_acceptance/strategy/file.rb
components/ruby/lib/license_acceptance/strategy/prompt.rb
components/ruby/lib/license_acceptance/strategy/provided_value.rb
components/ruby/license-acceptance.gemspec

Optimize the requires here to speed up requiring the library on systems

Convert to require_relative

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml

Use the build in gem caching in Expeditor

---

.expeditor/verify.pipeline.yml
components/ruby/Gemfile

Test on Ruby 3.0

---

.expeditor/run_windows_tests.ps1
.expeditor/verify.pipeline.yml

Signed-off-by: jayashri garud <jgarud@msystechnologies.com>

add windows tests 3.0/3.1
