components/ruby/lib/license_acceptance/prompt_acceptance.rb

Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>
Fixes a syntax error that occurs on Ruby 2.4 and 2.3:
```
bundler: failed to load command: inspec (/Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/inspec)
SyntaxError: /Users/cwolfe/sandbox/inspec/license-acceptance/components/ruby/lib/license_acceptance/prompt_acceptance.rb:79: syntax error, unexpected keyword_rescue, expecting keyword_end
rescue PromptTimeout
^
```
Added an explicit `begin`

Add explicit begin for Timeout block to support ruby < 2.5

---

components/ruby/Gemfile.lock
components/ruby/lib/license_acceptance/config.rb
components/ruby/license-acceptance.gemspec
components/ruby/spec/license_acceptance/config_spec.rb

Somehow it is overriding the 'windows?' helper method in the chef
codebase. Not sure how, but we only need 1 method so just importing
that.

tty-platform library is interfering with chef-client

---

.expeditor/config.yml
CHANGELOG.md

This is the default promote strategy for non-Omnibus packages.

Gem and Habitat packages only need unstable and stable releases

---

README.md
components/ruby/Gemfile.lock
components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/lib/license_acceptance/arg_acceptance.rb
components/ruby/lib/license_acceptance/cli_flags/mixlib_cli.rb
components/ruby/lib/license_acceptance/cli_flags/thor.rb
components/ruby/lib/license_acceptance/env_acceptance.rb
components/ruby/lib/license_acceptance/file_acceptance.rb
components/ruby/spec/license_acceptance/acceptor_spec.rb
components/ruby/spec/license_acceptance/arg_acceptance_spec.rb
components/ruby/spec/license_acceptance/env_acceptance_spec.rb
components/ruby/spec/license_acceptance/file_acceptance_spec.rb

Adds a new value that can be passed as a value to `--chef-license` or as an ENV var: `accept-silent`. If this value is seen, the license is accepted, persisted to disk, but no count of accepted licenses is emitted to STDOUT.
This solves a critical path issue with the A2 team: we cannot break pure JSON on STDOUT.
attn: @vjeffrey 
Closes #23.

Add silent license acceptance option

---

.expeditor/update_version.sh
.expeditor/verify.pipeline.yml
components/ruby/.gitignore
components/ruby/Gemfile.lock

Otherwise the version of the `license-acceptance` gem itself begins to drift
N/A

Expeditor should be updating the Gemfile.lock after bumping version

---

components/ruby/LICENSE
components/ruby/license-acceptance.gemspec

Add a license file for license scout
license scout can't find a license file in the gem artifact so it's failing our omnibus builds. We need to get it passing so we can build all our apps with license acceptance.
Nope

Add a license file for license_scout

---

.expeditor/verify.pipeline.yml
components/ruby/license-acceptance.gemspec

We shouldn't support EOL ruby 2.3 with this gem.
This requires we first merge in https://github.com/inspec/inspec/pull/3953

Require Ruby 2.4 or later

---

components/ruby/README.md
components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/lib/license_acceptance/product.rb
components/ruby/lib/license_acceptance/product_reader.rb
components/ruby/lib/license_acceptance/strategy/base.rb
components/ruby/spec/license_acceptance/acceptor_spec.rb
components/ruby/spec/license_acceptance/product_reader_spec.rb
components/ruby/spec/license_acceptance/product_spec.rb
product_info.toml

Test Kitchen knows products by their mixlib-install name so we add
support for that attribute to the product. We also expose methods to
interact with the products by that attribute. Finally, I added a
convenience method for Test Kitchen to know how the license was accepted
so it can pass that through to provisioned nodes.
N/A

Adding mixlib-install product search to enable Test Kitchen

---

.expeditor/verify.pipeline.yml
components/ruby/license-acceptance.gemspec

Adding back Ruby 2.3 support to prevent major version bumping Test Kitchen

---

components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/spec/license_acceptance/acceptor_spec.rb

In this case we assume they want the latest version which will require a
license.
N/A

TK can provide nil version to license_required?

---

.expeditor/verify.pipeline.yml
components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/lib/license_acceptance/product.rb
components/ruby/lib/license_acceptance/product_reader.rb
components/ruby/lib/license_acceptance/strategy/file.rb
components/ruby/lib/license_acceptance/strategy/prompt.rb
components/ruby/spec/license_acceptance/acceptor_spec.rb
components/ruby/spec/license_acceptance/product_reader_spec.rb
components/ruby/spec/license_acceptance/product_spec.rb
components/ruby/spec/license_acceptance/strategy/file_spec.rb
components/ruby/spec/license_acceptance/strategy/prompt_spec.rb
product_info.toml

This change started by updating the Infra products to `Chef Infra
Client` and `Chef Infra Server`.
In doing this I realized `name` was a bad identifier on the product and
changed it to `id`. This reflects the truth that this is an internal
identifier of a product. It could be a UUID but that would make other
developers jobs hard. `pretty_name` is the name we use when
communicating to users about these products.
N/A

Bringing names in line with marketing

---

components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/spec/license_acceptance/acceptor_spec.rb

For example: https://github.com/chef/chef/blob/master/kitchen-tests/kitchen.yml#L6
Without this change those tests now throw an error when trying to read that version using `Gem::Version`
N/A

mixlib supplies channel names as versions to install

---

product_info.toml

It appears that accepting chef client license doesn't transitively
accept inspec, and that's blocking chef-server-ctl. Add inspec.
Signed-off-by: Mark Anderson <mark@chef.io>

Add inspec to chef-server deps

---

README.md

Signed-off-by: Stuart Preston <stuart@chef.io>
Whilst Chef Infra Client and InSpec use `accepted_licenses`, Habitat uses `accepted-licenses`. This fixes the Readme to that effect for Windows. I have not tested this on other platforms.

Updating default license location for Habitat on Windows

---

components/ruby/license-acceptance.gemspec

Don't ship the specs, Rakefile, or Gemfile.lock in the gem artifact.

Limit the files we ship in the gem to reduce the install size

---

.expeditor/update_version.sh
components/ruby/lib/license_acceptance/acceptor.rb

```
+ bundle update license-acceptance
This Bundle hasn't been installed yet. Run `bundle install` to update and
install the bundled gems.
```
https://logs.cd.chef.co/raw/chef-license-acceptance-master-pull_request_merged-chef-license-acceptance-master-69-86cffa00-7e03-11ea-9fc0-8fc1e1f846b2

Fixing error with Expeditor update_version.sh script

---

.expeditor/verify.pipeline.yml
components/ruby/Gemfile
components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/lib/license_acceptance/cli_flags/mixlib_cli.rb
components/ruby/lib/license_acceptance/cli_flags/thor.rb
components/ruby/lib/license_acceptance/product.rb
components/ruby/lib/license_acceptance/strategy/prompt.rb
components/ruby/license-acceptance.gemspec

Test Kitchen 1 shipped in DK 3, which is now EOL. We can drop support
for Ruby 2.3 at this point and do a major version bump. This also sets
new floors for the tty-box and tty-prompt gems to resolve warnings on
Ruby 2.7+

Remove support for Ruby 2.3 and bump tty deps

---

components/ruby/spec/license_acceptance/product_reader_spec.rb

Signed-off-by: Pete Higgins <pete@peterhiggins.org>
`.to be_an_instance_of` calls `instance_of?` under the covers and neither takes a block, so these tests were not being run.

Fix product reader tests.

---

components/ruby/example/example_mixlib_cli_app.rb
components/ruby/lib/license_acceptance/acceptor.rb
components/ruby/lib/license_acceptance/strategy/argument.rb
components/ruby/lib/license_acceptance/strategy/environment.rb
components/ruby/lib/license_acceptance/strategy/provided_value.rb
components/ruby/spec/license_acceptance/acceptor_spec.rb
components/ruby/spec/license_acceptance/strategy/argument_spec.rb
components/ruby/spec/license_acceptance/strategy/environment_spec.rb
components/ruby/spec/license_acceptance/strategy/provided_value_spec.rb
components/ruby/spec/spec_helper.rb

Signed-off-by: Pete Higgins <pete@peterhiggins.org>
When a user attempts to satisfy the license acceptance requirements with an unrecognized value, print an error message and quit instead of prompting them for acceptance with no indication of what went wrong.
This PR adds an example CLI app using the license-acceptance library for easier testing in development, without having to muck with the dependencies of infra client, inspec, etc.
The happy path of using a good value for license acceptance works:
```
Petes-MBP:ruby pete$ ./example/example_mixlib_cli_app.rb --chef-license=accept-no-persist
BIG SUCCESS
```
If the user uses an unrecognized value for license acceptance they get an error message and the app exits:
```
Petes-MBP:ruby pete$ ./example/example_mixlib_cli_app.rb …
```

Fail license acceptance if the user provides an unrecognized value

---

components/ruby/lib/license_acceptance/strategy/file.rb
components/ruby/lib/license_acceptance/strategy/provided_value.rb
components/ruby/spec/license_acceptance/strategy/argument_spec.rb
components/ruby/spec/license_acceptance/strategy/environment_spec.rb
components/ruby/spec/license_acceptance/strategy/provided_value_spec.rb

Then env and argument strategies checked the value case insensitively while the provided value strategy didn't. This adds tests to all 3 to make this behavior explicit and changes the provided value strategy to match the other two.

Case insensitively check acceptance

---

components/ruby/Gemfile
components/ruby/Rakefile

The parallel gem added back Ruby 2.4 support so we can nuke this pin now

Remove yard tasks / unpin parallel gem
